### ISSUE TITLE
Problems building in IntelliJ IDEA 2021.1

### ISSUE THREAD

**Issue by skress** [killbill/killbill-oss-parent#176]
I am currently having trouble building the Stripe plugin with IntelliJ IDEA 2021.1. As there is a .idea folder in your repositories, it looks like you are also using IntelliJ IDEA.

I have recently upgraded to IntelliJ 2021.1 and now building a project inside the IDE does not work anymore. It seems like Jetbrains changed something internally which now triggers a bug in an older version of manifold that is used in killbill-oss-parent. 

Some more information can be found here: https://youtrack.jetbrains.com/issue/IDEA-266798. I don't know if Jetbrains will change anything on their side.

Upgrading manifold from 2020.1.45 to 2021.1.11 resolved the issue for me. But I only tested it to compile the Stripe plugin. I don't know if upgrading manifold will lead to problems in any of your other projects.

It would be great if you could consider upgrading manifold next time you are upgrading your dependencies.

**Comment by pierre** [comment]
Thanks for the report! I've created https://github.com/killbill/killbill-oss-parent/pull/177.
