### ISSUE TITLE
Update snakeyaml dependency version

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-oss-parent#711]
The `snakeyaml` dependency needs to be updated to `2.0`. The current version (`1.33`) has some vulnerabilities which is causing an issue for some customers.

**Comment by xsalefter** [comment]
@reshmabidikar shouldn't this closed by this? 1a099ea61d002e9bae8b0935c01b463da45936aa

**Comment by reshmabidikar** [comment]
Yes, you are right @xsalefter, looks like I missed closing it earlier, closing it now!
